### ISSUE TITLE
CreateStorageIfNotExists hangs

### ISSUE THREAD

**Issue by mhollier** [HealthCatalyst/InstallScripts#35]
I think there may also be an issue with the function *CreateStorageIfNotExists*. If I accept the default it works.

However, if I enter an alternative (e.g. meh-k8s-rt-rg) which does not exist, then it prompts _Storage account, [meh-k8s-rt-rg], already exists.  Deleting it will remove this data permanently_... I answer _y_ to the *Delete storage account* prompt and then it hangs.

My guess is is the `az storage account delete` is attempting to delete a non-existing storage account and hangs or maybe an unhandled error somewhere? I don't see any errors logged though.

**Comment by imranq2** [comment]
should be fixed now
