### ISSUE TITLE
DownloadFile function used by the create-bare-metal.ps1 is extremely slow

### ISSUE THREAD

**Issue by mhollier** [HealthCatalyst/InstallScripts#37]
The DownloadFile function used by the create-bare-metal.ps1 is extremely slow (~500Kbps) which makes the download of kubectl.exe take a very long time. As a workaround, you may download https://storage.googleapis.com/kubernetes-release/release/v1.9.2/bin/windows/amd64/kubectl.exe and place in the c:\kubernetes folder.

**Comment by imranq2** [comment]
fixed by switching to webclient
